-- 코드를 입력하세요
SELECT A.REST_ID
,REST_NAME
,fOOD_TYPE
,FAVORITES
,ADDRESS
,ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A
JOIN REST_INFO B ON B.REST_ID = A.REST_ID
GROUP BY A.REST_ID
HAVING ADDRESS LIKE'서울%'
ORDER BY SCORE DESC, FAVORITES DESC