SELECT 
    p.PRODUCT_ID AS 식품ID, 
    p.PRODUCT_NAME AS 식품이름, 
    SUM(o.AMOUNT * p.PRICE) AS 총매출
FROM 
    FOOD_PRODUCT p
JOIN 
    FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE 
    DATE_FORMAT(o.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY 
    p.PRODUCT_ID
ORDER BY 
    총매출 DESC, 
    p.PRODUCT_ID ASC